# Generated by Django 2.1.3 on 2018-11-13 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billsplit', '0003_transaction_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('time', models.DateTimeField(verbose_name='Transaction Time')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billsplit.Group')),
                ('paidBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paidBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='group',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='time',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='title',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bill',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='billsplit.Bill'),
            preserve_default=False,
        ),
    ]
