# Generated by Django 2.1.3 on 2018-11-13 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billsplit', '0004_auto_20181113_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillSharer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billsplit.Bill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='lender',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
